language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false)
  email:
    recipients:
    - hexileee@gmail.com
  on_success: change
  on_failure: always

go:
- "1.11"

install:
- go build
- go get github.com/mattn/goveralls


script: # 集成脚本
- go test -bench=.
- go test ./... -v -cover -race -coverprofile=go.coverprofile
- goveralls -coverprofile=go.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN

after_success:
- bash <(curl -s https://codecov.io/bash)

env: #env环境变量设置，travis提供的repo_token安全方式
  global:
    secure: "VfYSWjT/vD/EtNQ9EdXLi17fxVq2C0VYMQgkJQPPRDpwAJq1nruTGX+2IhjXidRx2xXaFVDXxXza+OnzFjW0+6NSlErnIg/vl8cDcIr386Em218yHcD4oTZhdnIbMhku3y3jziITtzSx07dbPndo6mmnEiidYODXteNq7i5qQWoZNcJi0TDe2mdK2QJzpS2p9y1Y1Au87yfO7/JtWd5WoFb6PRAMZsCSwXUD3VJoSS9WBT3bUEE+M3hPnPn+XFvzFUi3FL60ia9eoUPgJUS3cYg7BFBBjQg3shBqo6uIZTMDaDFQoTSpy2sJi90hLl/rKOfXFWuEYGRlMLNUcP+OYYFsQQN/obBPRLSOR7x4lnJq5Cw7zMdfj8nxtF6c4RAPgagSREXJpqw9G8KuxQx6HkObn+DdmR8AQdPPX9ok8lvmAjnPRpn9OWKntXH6rB/Mr+fkIrMsnrJDLfB97pV6SvNYBeSpN2jWZrvg0G3oc8g/xVKOThq0UNNlBqv02OwSgRtJbEmi8Xa7cG+WA/W+YYjmZXCqHtDsZBfOKR3laENAAh4PRYz0DnO6R30KJqZHyOaLgOxDIkdiXvPo3dkh8uNS7BFr/IKMScmXLssxKETlHGd1FMSWabxLGyjFOg0vyuRJ5wikYz7PtqfNb5Kuxo9dsl2oLjg8YD83Sx7uKQE="
